repos:
  - repo: https://github.com/astro/deadnix
    rev: v1.2.0
    hooks:
      - id: deadnix
        args: [--edit]
        stages: [commit]
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
    - id: alejandra
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    - id: shellcheck
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.2
    hooks:
      - id: stylua # or stylua-system / stylua-github
