name: Update Checksums

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  update-checksums:
    if: contains(github.event.pull_request.labels.*.name, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated dependency
        run: |
          #!/usr/bin/env bash

          set -x

          dependency=$(git diff origin/main..HEAD "*.nix" | grep + | grep renovate)
          rev=$(echo "$dependency" | awk -F ' ' '{print $4}')
          rev=${rev#\"}

          echo "rev=${rev%\";}" >> $GITHUB_ENV
          echo "repo=$(echo "$dependency" | grep -o 'depName=[^ ]*' | cut -d= -f2)" >> $GITHUB_ENV

      - name: Download archive
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          mkdir archive
          cd archive
          curl -sSL --fail https://github.com/${{ env.repo }}/archive/${{ env.rev }}.tar.gz | tar xz --strip-components=1
          pwd
          ls -lrta

      - name: Get checksum
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: nixos/nix
          options: -v ${{ github.workspace }}:/work
          run: |
            nix --extra-experimental-features nix-command hash path /work/archive > /work/checksum
            ls -l /work

      - name: Check if checksum must be updated
        id: check_checksum
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          filename=$(git diff --name-only origin/main..HEAD "*.nix" | head -1)

          sha_new=$(cat /home/runner/work/nix-config/nix-config/checksum)

          line=$(cat $filename | grep depName=$repo | grep sha256)

          sha_old=$(echo $line | awk -F ' ' '{ print $3 }')
          sha_old=${sha_old#\"}
          sha_old=${sha_old%\";}

          if [ "$sha_old" = "$sha_new" ]; then
            echo "sha-256 for {{ $env.repo }} : {{ $env.rev }} is already up to date."
          else
            echo "sha-256 for {{ $env.repo }} : {{ $env.rev }} must be updated."
            echo "update_checksum=true" >> $GITHUB_OUTPUT
            echo "filename=$filename" >> $GITHUB_ENV
            echo "sha_old=$sha_old" >> $GITHUB_ENV
            echo "sha_new=$sha_new" >> $GITHUB_ENV
          fi

      - name: Update dependency with new checksum
        if: steps.check_checksum.outputs.update_checksum == 'true'
        run: |
          #!/usr/bin/env bash

          sed -i 's/$sha_old/$sha_new/g' ${{ env.filename }}

          grep $sha_new ${{ env.filename }}

      - name: Commit
        if: steps.check_checksum.outputs.update_checksum == 'true'
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          file_pattern: '*.nix'
