name: Update Checksums

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  update-checksums:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Pull Request comes from renovate
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          gh api -H "Accept: application/vnd.github+json" /repos/auricom/nix-config/issues/${{ github.event.pull_request.number }}/labels | jq '[.[].name]' > /tmp/label_list

          if grep -q "checksums_needed" /tmp/label_list; then
            echo "check_checksums=true" >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: ${{ env.check_checksums == 'true' }}
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated dependency
        if: ${{ env.check_checksums == 'true' }}
        run: |
          #!/usr/bin/env bash

          set -x

          dependency=$(git diff origin/main..HEAD "*.nix" | grep + | grep renovate)
          rev=$(echo "$dependency" | awk -F ' ' '{print $4}')
          rev=${rev#\"}
          rev=${rev%\";}

          echo "rev=$rev" >> $GITHUB_ENV
          echo "repo=$(echo "$dependency" | grep -o 'depName=[^ ]*' | cut -d= -f2)" >> $GITHUB_ENV

          if [[ "$dependency" == *"fetchurl"* ]]; then
            echo "fetch_url=true" >> $GITHUB_ENV
            filename=$(git diff --name-only origin/main..HEAD "*.nix" | head -1)
            line=$(cat $filename | grep "url =")
            url=$(echo $line | awk -F ' ' '{ print $3 }')
            url=${url#\"}
            url=${url%\";}
            url=${url/\${version\}/$rev}
            url=${url/\${version_mod\}/${rev#v}}
            echo "url=$url" >> $GITHUB_ENV
          fi

      - name: fetchFromGitHub | Download archive
        if: ${{ env.check_checksums == 'true' && env.fetch_url != 'true' }}
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          mkdir archive
          cd archive
          curl -sSL --fail https://github.com/${{ env.repo }}/archive/${{ env.rev }}.tar.gz | tar xz --strip-components=1
          pwd
          ls -lrta

      - name: fetchFromGitHub| Get checksum
        if: ${{ env.check_checksums == 'true' && env.fetch_url != 'true' }}
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: nixos/nix
          options: -v ${{ github.workspace }}:/work
          run: |
            nix --extra-experimental-features nix-command hash path /work/archive > /work/checksum
            ls -l /work

      - name: fetchurl | Get checksum
        if: ${{ env.check_checksums == 'true' && env.fetch_url == 'true' }}
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: nixos/nix
          options: -v ${{ github.workspace }}:/work
          run: |
            curl -sSL --fail --output /tmp/file ${{ env.url }}
            nix --extra-experimental-features nix-command hash file /tmp/file > /work/checksum
            ls -l /work

      - name: Check if checksum must be updated
        if: ${{ env.check_checksums == 'true' }}
        run: |
          #!/usr/bin/env bash
          set -x

          filename=$(git diff --name-only origin/main..HEAD "*.nix" | head -1)

          sha_new=$(cat /home/runner/work/nix-config/nix-config/checksum)

          line=$(cat $filename | grep depName=$repo | grep hash)

          sha_old=$(echo $line | awk -F ' ' '{ print $3 }')
          sha_old=${sha_old#\"}
          sha_old=${sha_old%\";}

          if [ "$sha_old" != "$sha_new" ]; then
            echo "update_checksum=true" >> $GITHUB_ENV
            echo "filename=$filename" >> $GITHUB_ENV
            echo "sha_old=$sha_old" >> $GITHUB_ENV
            echo "sha_new=$sha_new" >> $GITHUB_ENV
          fi

      - name: Update dependency with new checksum
        if: ${{ env.update_checksum == 'true' }}
        run: |
          #!/usr/bin/env bash
          set -x

          sed -i 's#${{ env.sha_old }}#${{ env.sha_new }}#g' ${{ env.filename }}

          grep $sha_new ${{ env.filename }}
          git diff

      - name: Commit
        if: ${{ env.update_checksum == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          file_pattern: '*.nix'
          disable_globbing: true
